### ISSUE TITLE
why controlling_process need Locks a mutex

### ISSUE THREAD

**Issue by SisMaker** [emqx/quic#106]
The controlling_process nif implementation is Locks a mutex，According to my understanding, controlling_process can only call this function if it originally owns the process, there will be no concurrent operation, Should there be no lock operation?

**Comment by qzhuyan** [comment]
We have another concurrent player which is the MsQuic Worker thread handling callback that might change the ownership concurrently.

Do you meet any issue or?

**Comment by SisMaker** [comment]
> 



> We have another concurrent player which is the MsQuic Worker thread handling callback that might change the ownership concurrently.
> 
> Do you meet any issue or?

I'm just curious why is it locked, no any issue.
