### ISSUE TITLE
multiple connects fail

### ISSUE THREAD

**Issue by klacke** [emqx/quic#120]
I'm seeing an error I cannot understand. A client that issues a series of `connect()` calls, it always fails on connection number 495. 

[quicer.tar.gz](https://github.com/emqx/quic/files/9664238/quicer.tar.gz)

The little test program attached can be used to reproduce. Run qt.erl and issue `{connect, 500}.` in the client

**Comment by klacke** [comment]
Found it, it was a ulimit issue, if I do e.g `ulimit -n 10000` it works much better. However, I think the bug still stands. For two reasons.
1. Bad unknown error message
2. I think the error somehow is poorly handled, just try it out and see for yourself.

**Comment by klacke** [comment]
The error is:
`{error,transport_down,{unknown_quic_status,24}}`

**Comment by klacke** [comment]
24 is EMFILE

**Comment by qzhuyan** [comment]
thanks for reporting, so it is still about number of FDs?

BTW, there is a limitation that the FD will get closed only when GC of the handler is triggered.

**Comment by klacke** [comment]
Yes this is about number of filedescriptors, and then about how the NIF handles the error EMFILE

**Comment by qzhuyan** [comment]
That is the errno that returns from OS, pass through Msquic(the quic C library) and quicer NIF, and eventually returns to the caller. I would suggest we leave it as it is. 

We could 'try' to translate the errno but our NIF get it from Msquic which is not transparent to NIF from OS.

Or what do you suggest?

**Comment by klacke** [comment]
I agree that it can be left as is. Mapping the OS errors is maybe overkill.
One minor change might be the right thing to do though, and that is to
change the atom unknown_quic_status to os_error, or posix_error or some
such in order to guide the user in the right direction. After all 24 is
EMFILE, and had the atom been something but unknown_quic_status I'd been
able to easily realize what was up.

**Comment by qzhuyan** [comment]
During my test, I found we could not just map unknown errno to `posix_error` because for instance due to different TLS implementations, the errno is different on MacOS and Linux for same TLS error:

FYI:
https://github.com/emqx/quic/pull/121/commits/5c2f24228057b3b085f12dc05b85042771fa5c3d

Yes MsQuic just shift the errno made it hard to find out without looking into its code.
what about just doc how to deal with `unknown_quic_status` and also shift back the errno to TLS errno (in above case)?

**Comment by klacke** [comment]
Sounds good

/klacke
