### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by helloyan** [emqx/quic#145]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ATOMIC
    linked by target "quicer_static" in directory /usr/src/emqx5/_build/default/lib/quicer

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
make[1]: *** [Makefile:11: build-nif] Error 1
make[1]: Leaving directory '/usr/src/emqx5/_build/default/lib/quicer'
===> Hook for compile failed!

**Comment by qzhuyan** [comment]
@helloyan look like libatomic is missing.

**Comment by qzhuyan** [comment]
close due to inactive
