### ISSUE TITLE
quic:connect()

### ISSUE THREAD

**Issue by klacke** [emqx/quic#150]
If quic:connect() fails nicely with for example 
```
{error,transport_down,
                            #{error => 1,status => unreachable}}
```

an unnecessary  message

```
{quic,closed,#Ref<0.1073868949.2575171596.191148>,
            #{is_app_closing => false,is_handshake_completed => false,
              is_peer_acked => true}}
```

is subsequently sent to the caller. 

I find this weird, the call has already failed. Also the flag `is_peer_acked` is confusing.

**Comment by qzhuyan** [comment]
thanks for reporting, 
Indeed, when the connect is not opened successfully.  The `{quic, closed, _, _ }' message is very dummy. We can skip sending it if quicer knows the `quicer:connect` call was failed or we just block for this message then return.

for `is_peer_acked` it is set by MsQuic I think.
