### ISSUE TITLE
Getting cert_untrusted_root

### ISSUE THREAD

**Issue by DanielViniciusAlves** [emqx/quic#158]
I'm trying to create a simple program to test the library. I already created the cert and key files but when I try to connect the client with the server the following error is shown: 
`** (MatchError) no match of right hand side value: {:error, :transport_down, %{error: 304, status: :cert_untrusted_root}}
    (quic 0.1.0) lib/quic.ex:16: Quic.client_start/0
`
I'm quite new to Quic, so maybe this is a silly issue, but It would be quite helpful if someone could give me some guidence.

**Note: I'm using the library with Elixir, don't know if this could be the problem.**

**Comment by qzhuyan** [comment]
Thanks for reporting.

Wonder which library do you use? it states `quic 0.1.0` but we don't have any tag of `0.1.0`

Could you share the opts you pass in when you do `connect` call? the `cacertfile` should be provided. 

Or try set `verify` to `none` to bypass the certificate check.

**Comment by DanielViniciusAlves** [comment]
So, answering the first question I'm importing the library with: `{:quicer, github: "emqx/quic"}` in elixir, described in [here](https://elixirschool.com/en/lessons/intermediate/erlang#erlang-packages-1).

The test program that I'm building following ping pong example is being defined as:
```
defmodule Quic do
  def server_start do
    options = [{:cert, "./server.cert" |> to_charlist}, {:key,  "./server.key" |> to_charlist}, {:alpn, ["sample" |> to_charlist]}, {:peer_bidi_stream_count, 1}]

    {:ok, pid} = :quicer.listen(4000, options)
    {:ok, conn} = :quicer.accept(pid, [], 12000000)
    {:ok, conn} = :quicer.handshake(conn)
    {:ok, stm} = :quicer.accept_stream(conn, [])
  end

  def client_start do
    {:ok, pid} = :quicer.connect("localhost" |> to_charlist, 4000, [{:alpn, ["sample" |> to_charlist]}], 5000)
    # {:ok, stm} = :quicer.start_stream(pid, [])
    # {:ok, test} = :quicer.send(stm, "ping" |> to_char_list)
    IO.inspect pid
  end
end

```

There are any documentation on the available options that I can pass in the functions call? I wasn't aware of the option verify none, I will give a try.

**Comment by qzhuyan** [comment]
doc is updated in #159
