### ISSUE TITLE
connect() hangs indefinitely

### ISSUE THREAD

**Issue by klacke** [emqx/quic#169]
Hi, 
I have a situation in our local system where quicer:connect() with a timeout of 10000 hangs indefinitely.
The stack dump is:
```
 {messages,
     [connect,
      {'$gen_call',
          {<0.330.0>,#Ref<0.787081997.2662072321.82090>},
          {new_up_stream,<0.330.0>}},
      {'$gen_call',
          {<0.331.0>,#Ref<0.787081997.2662072321.82091>},
          {new_up_stream,<0.331.0>}}]},
 {current_stacktrace,
     [{quicer,flush,2,[{file,"src/quicer.erl"},{line,981}]},
      {quicer,connect,4,[{file,"src/quicer.erl"},{line,227}]},
      {volga_q_connector,conn_list,3,
          [{file,"src/volga_q_connector.erl"},{line,134}]},
      {volga_q_connector,handle_info,2,
          [{file,"src/volga_q_connector.erl"},{line,173}]},
      {gen_server,try_dispatch,4,
          [{file,"src/gen_server.erl"},{line,1123}]},
      {gen_server,handle_msg,6,
          [{file,"src/gen_server.erl"},{line,1200}]},
      {proc_lib,init_p_do_apply,3,
          [{file,"proc_lib.erl"},{line,240}]}]}]
```
The messages in the queue are of course local to our system. I've tried to reproduce this in the quicer tests to no avail. Regardless, the stackdump is proof of error imho. It's a reconnect situation, where a previous connection to another host has just died.
Opinions please.

**Comment by klacke** [comment]
If you want, I can send a PR for my nonworking reproduction attempts

**Comment by qzhuyan** [comment]
what value of `idle_timeout_ms` do you use? default is a few mins.
also, try commenting out `quicer.erl"},{line,227 ` and check what Is the returned error atom?

**Comment by klacke** [comment]
15000
Will try the lib change

**Comment by klacke** [comment]
Reason = #{error => 1,status => unreachable}

**Comment by qzhuyan** [comment]
How fast it returns? Is it 100% reproducible? 
Looks works fine on my node. (port 14569 has no UDP listener on it).
```
quicer:connect("127.0.0.1", 14568,[{alpn, ["mqtt"]}], 1000).
{error,transport_down,#{error => 1,status => unreachable}}
```

is there any firewall that blocked the dest port?

**Comment by klacke** [comment]
No, highly erratic, happens randomly inside our local tests, no fw inbetween. The scenarios I have that fail with the above hanging stackdump fails 1 out of 5 or 10.

**Comment by klacke** [comment]
Well returns, the problem is that it never returns. Or do you mean the call to async_connect()

**Comment by klacke** [comment]
What triggers unreachable, i.e exactly what is that error. I'm thinking to try to reproduce in an easier env

**Comment by klacke** [comment]
Is that the equivalent of ECONNREFUSED

**Comment by qzhuyan** [comment]
looks to me that the `quicer_nif:async_connect` returns but we are expecting the async result from receiving the message. 
looks like the result is negative so we are flushing the `{quic, close, Handle, _}`
the problem is you didn't get this `{quic, close, ...}` message which it should have for the reason `unreachable`. I suspect it is something else (other reason).

**Comment by qzhuyan** [comment]
> Is that the equivalent of ECONNREFUSED

`unreachable` means the port is not opened or host is not opened from ICMP reply. Also DNS could trigger such issue as well. are you connecting with hostname or IP?

**Comment by qzhuyan** [comment]
> I can try that, see if I get any other msg from that H and print it

FYI, `process_info(Pid, messages)` should tell. 

do you call `controlling process` in between? maybe the `{quic, close...}` msg went to other pid?

**Comment by klacke** [comment]
IP

**Comment by klacke** [comment]
No, I'm not using controlling_process on the Connections (which btw doesn't work, as per the PR I sent)
I'm using handoff on streams a lot though, but this is prior to any streams exist, it's connect().

**Comment by klacke** [comment]
yes you are right, any other msgs would have shown in the stack trace

**Comment by klacke** [comment]
In general though, the branch in the code with unreachable works fine it seems, on a run of my failing testcase I get quite a few of the unreachable errors before it hangs

**Comment by qzhuyan** [comment]
can I ask what makes it unreachable?

If the peer side is also quicer, it could happen that there is no conn acceptor in the queue and quicer will just reject new conn but I am not sure if the client will get `unreachable`.

**Comment by qzhuyan** [comment]
Yes, it is.
https://github.com/emqx/quic/blob/main/c_src/quicer_listener.c#L93

So maybe change this status to another error code? But still I think we should get the connection close.

**Comment by klacke** [comment]
connect() gets error unreachable when the other end, which is also quicer, restarts, sometimes.

**Comment by klacke** [comment]
Well, In my code, i'm certainly the conn_owner, especially since it's connect() that fails, no other processes involved. The old (dead) and removed connection, did have streams in other processes though, but only one process ever owns the Connection

**Comment by klacke** [comment]
No acceptor case is interesting though, I don't have an acceptor running at all times, will try to have that.

**Comment by qzhuyan** [comment]
any updates? Unfortunately, I can't reproduce the issue you mentioned. 
even when peer node crashes, we should still get {quic, closed, ....} event .

If you have any lux script that could show me the test that will help even 1% chance to reproduce.

**Comment by klacke** [comment]
Unfortunately no, I've tried hard to reproduce outside of our system, to no
avail.

/klacke

**Comment by klacke** [comment]
I haven't seen this is a long time now. If you want to, you can close this
