### ISSUE TITLE
Getting the negotiated ALPN protocol

### ISSUE THREAD

**Issue by essen** [emqx/quic#196]
Hello! Another thing I noticed was missing is the equivalent of ssl:negotiated_protocol to retrieve the ALPN protocol that was selected. For HTTP/3 for example the selected protocol should be "h3".

**Comment by qzhuyan** [comment]
thanks for raising this issue. We will add new API for `quicer:negotiated_protoco/1`

meanwhile you could try `quicer:getopt(Conn, param_tls_negotiated_alpn, quic_tls)`

example in test:
https://github.com/emqx/quic/blob/main/test/quicer_SUITE.erl#L1846

**Comment by essen** [comment]
Ah I had not seen this. Thanks. In that case a separate function may not be necessary.

**Comment by qzhuyan** [comment]
> Ah I had not seen this. Thanks. In that case a separate function may not be necessary.

it will be nice to have it anyway!
