### ISSUE TITLE
Providing our own stream reference for quicer:start_stream

### ISSUE THREAD

**Issue by essen** [emqx/quic#216]
Hello, I was thinking it would be great if the reference that is returned by quicer:start_stream could be provided by the user instead. For example in Gun I already have a reference when creating a request, before QUIC is involved, therefore having a second reference for what is essentially the same thing is a bit of a waste (a bidi stream = 1 request/response in HTTP/3 = 1 Gun stream reference).

**Comment by qzhuyan** [comment]
the reference return from `quicer:start_stream` in erlang world they are NIF resource (assigned by OTP),  and they are just pointers point to different heap memory in C world. So these references are not simply erlang references they are backed by some heap data used by NIF. 

Actually quicer should not expose this type(reference) as it should be `opaque`.  just take it as the stream handle.

These references are manageable by OTP as part of the erlang <-> C interface and they could change type in the future from my understanding.

**Comment by essen** [comment]
Yes I know but I was thinking that perhaps we could provide a reference that would be used everywhere instead of the NIF resource reference (though we do want this reference returned so we can store it somewhere). Like when sending data or when receiving messages. Might be too much complexity for the NIF though.

**Comment by qzhuyan** [comment]
what about new API, `open_stream(connecion_handle())` return a `{ok, stream_hanle()}` where the stream is located in the specified `connecion` but neither of them yet started?

**Comment by essen** [comment]
Don't think that's a good idea because that reference is passed around between processes in Gun and that would break the separation of concerns by having the stream handle in more than one process (and perhaps the connection handle as well).

For now I will just have a map from reference to stream handle.

Anyway don't worry too much about this it's more a "would be nice if" than anything.

**Comment by qzhuyan** [comment]
Indeed, we should avoid copying the stream/connecion handles in many places, then should be managed because QUIC relies on GC to free the handle in quicer NIF context.

Please point me to some points in GUN code, that might help me understand, also for the future planning.

**Comment by essen** [comment]
When requests come in this code is run (either headers or request), https://github.com/ninenines/gun/blob/master/src/gun.erl#L627-L663

The `make_ref()` at the bottom is the one that I will map to the stream handle.

This reference (or a list of reference if tunnels are involved) is sent with every message from or to Gun, and is used to identify streams internally.

**Comment by essen** [comment]
Let's drop this, I have switched to isolating the quicer ref and am using the stream ID internally. I think it's more sane than whatever I was thinking here. Cheers.
