### ISSUE TITLE
Can't get stream ID after receiving stream_closed message

### ISSUE THREAD

**Issue by essen** [emqx/quic#226]
This no longer works on main:

```
receive
         {quic, stream_closed, StreamRef, Flags} →
             {ok, StreamID} = quicer:get_stream_id(StreamRef),
             ...
end
```

Before I could get the StreamID, now I can't. It's fine if we can't use the StreamRef anymore, but I would expect to be able to retrieve metadata at least.

I guess it's not a big deal since I can get it from my state but it's surprising.

**Comment by qzhuyan** [comment]
thanks for reporting.
yes. this is expected as we close the handle in msquic when we close the stream, we no longer have access to that stream.
 
I think this should be the only case that you cannot fetch stream id with a `StreamRef`.

I am trying to avoid duplicated info in our NIF and in the msquic. Could you fetch the stream id earlier (before stream get closed)?

maybe we can also add a option that do not 'auto' close stream in NIF.  We do this auto thing for two reasons: 
1. support hot upgrade, all handle must be closed.
3. release memory as soon as possible, old implementation waits for the GC to free.

**Comment by essen** [comment]
Yes as I mentioned it's not a big deal for me it's just surprising. I wouldn't expect any other value to be available after the stream has closed, but the stream ID is the protocol equivalent of the NIF object (StreamRef) so I don't think that ID should be gone just because the stream has closed.

The auto-close change is good and I agree info should not be duplicated, except for this one. I would recommend keeping the stream ID alongside the handle. This will be useful not just for applications but for debugging as well since this ID is what we have when looking at packets directly (via wireshark or other). You seem to have a bunch of reserved fields as well in the struct so there should be no extra cost to having it there.

**Comment by qzhuyan** [comment]
I see. I will impl that!

**Comment by essen** [comment]
Another problem caused by this is as follow:

* Server sends data
* Server closes stream
* Client receives data
* Client calls `quicer:get_stream_id` and gets an `{error, closed}` back
** Client can't process the data that it received before the stream was closed

In HTTP/3 I believe this happens due to the client aborting sending when it has finished sending the request, then the server aborting its own sending when it has finished sending the response, as has to be done according to the spec (below). The problem is that the client cannot retrieve the stream ID even if it hasn't finished processing all data.

> An HTTP request/response exchange fully consumes a client-initiated bidirectional QUIC stream. After sending a request, a client MUST close the stream for sending. [...] After sending a final response, the server MUST close the stream for sending. At this point, the QUIC stream is fully closed.

It appears the only time it's safe to call `quicer:get_stream_id` right now is immediately after the stream is opened.

**Comment by essen** [comment]
Thank you!
