### ISSUE TITLE
Calling quicer from iex

### ISSUE THREAD

**Issue by adrianbrink** [emqx/quic#233]
I'm currently trying to run the example and open a connection from my iex shell.

```
:quicer.listen(22, %{:cert => "./domain.pem", :key => "./domain.key", :alpn => ["sample"], :verify => :none})
{:error, :quic_tls}
```

I'm generating the keys with:
```
openssl genrsa -out keypair.pem 2048
openssl x509 -in domain.crt -out domain.pem -outform PEM
```

I think either I'm using broken keys or I'm incorrectly calling Erlang from Elixir.

A quick example of how to do it correctly would be appreciated.

**Comment by qzhuyan** [comment]
`{:error, :quic_tls}` means the issue from TLS layer. 

1, if you are using latest main branch, you should use `:keyfile` and `:certfile`. 
2. port 22 looks suspicious, it may not success without sudo. try some port number > 1024
3. you could use following command to generate the keys
```
openssl req  -nodes -new -x509  -keyout server.key -out server.cert
```

**Comment by adrianbrink** [comment]
I'm on this commit (which is on `main` from 3 days ago `9dbb916971e1d9f837a519caf7c993c17fc88dd0`.

I generated the keys according to your above command.

I'm running this and receiving a different error:
```
iex(foo@two)7> :quicer.listen(4567, [certfile: './priv/server.cert', keyfile: './priv/server.key', alpn: ['sample'], verify: false])
{:error, :config_error, :tls_error}
```
I changed `"` to `'` since it seems that Elixir and Erlang streams are different and working with Erlang seems to require `'`.

**Comment by adrianbrink** [comment]
Can confirm that it works now. Thank you
