### ISSUE TITLE
OTP-27 compatibility

### ISSUE THREAD

**Issue by essen** [emqx/quic#271]
Please update snabbkaffe to 1.0.10 for OTP-27 compatibility.

https://github.com/kafka4beam/snabbkaffe/issues/63

Alternatively, I think you're only using this for testing, right? Could it be made to only load when running tests, so that it isn't required when using quicer as a dependency?

Thank you.

**Comment by qzhuyan** [comment]
We use some Marcos from snabbkaffe for logging/tracing.

**Comment by essen** [comment]
Fair enough.
