### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by jlungerer** [emqx/quic#275]
CMake Error at /usr/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/home/jungerer/repositories/emqx/deps/quicer/c_build/CMakeFiles/CMakeScratch/TryCompile-xnr6ow'
    
    Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_110ac/fast
    gmake[2]: Entering directory '/home/jungerer/repositories/emqx/deps/quicer/c_build/CMakeFiles/CMakeScratch/TryCompile-xnr6ow'
    /usr/bin/gmake  -f CMakeFiles/cmTC_110ac.dir/build.make CMakeFiles/cmTC_110ac.dir/build
    gmake[3]: Entering directory '/home/jungerer/repositories/emqx/deps/quicer/c_build/CMakeFiles/CMakeScratch/TryCompile-xnr6ow'
    Building CXX object CMakeFiles/cmTC_110ac.dir/testCXXCompiler.cxx.o
    /usr/bin/c++   /home/jungerer/repositories/otp/erts  -o CMakeFiles/cmTC_110ac.dir/testCXXCompiler.cxx.o -c /home/jungerer/repositories/emqx/deps/quicer/c_build/CMakeFiles/CMakeScratch/TryCompile-xnr6ow/testCXXCompiler.cxx
    c++: warning: /home/jungerer/repositories/otp/erts: linker input file unused because linking not done
    Linking CXX executable cmTC_110ac
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_110ac.dir/link.txt --verbose=1
    /usr/bin/c++ /home/jungerer/repositories/otp/erts  CMakeFiles/cmTC_110ac.dir/testCXXCompiler.cxx.o -o cmTC_110ac
    /usr/bin/ld: cannot find /home/jungerer/repositories/otp/erts: file format not recognized
    collect2: error: ld returned 1 exit status
    gmake[3]: *** [CMakeFiles/cmTC_110ac.dir/build.make:99: cmTC_110ac] Error 1
    gmake[3]: Leaving directory '/home/jungerer/repositories/emqx/deps/quicer/c_build/CMakeFiles/CMakeScratch/TryCompile-xnr6ow'
    gmake[2]: *** [Makefile:127: cmTC_110ac/fast] Error 2
    gmake[2]: Leaving directory '/home/jungerer/repositories/emqx/deps/quicer/c_build/CMakeFiles/CMakeScratch/TryCompile-xnr6ow

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

**Comment by qzhuyan** [comment]
It should use c compiler not c++.

**Comment by jlungerer** [comment]
now it seems to compile -> closed
