### ISSUE TITLE
mix deps.compile quicer fails

### ISSUE THREAD

**Issue by jlungerer** [emqx/quic#276]
In file included from /home/jungerer/repositories/emqx/deps/quicer/c_src/quicer_connection.h:21,
                 from /home/jungerer/repositories/emqx/deps/quicer/c_src/quicer_connection.c:16:
In function ‘EncodeHexBuffer’,
    inlined from ‘dump_sslkeylogfile’ at /home/jungerer/repositories/emqx/deps/quicer/c_src/quicer_connection.c:210:7:
/home/jungerer/repositories/emqx/deps/quicer/msquic/src/inc/msquichelper.h:268:28: error: writing 16 bytes into a region of size 1 [-Werror=stringop-overflow=]
  268 |         HexString[i*2 + 1] = HEX_TO_CHAR(Buffer[i] & 0xf);
      |                            ^
/home/jungerer/repositories/emqx/deps/quicer/c_src/quicer_connection.c: In function ‘dump_sslkeylogfile’:
/home/jungerer/repositories/emqx/deps/quicer/c_src/quicer_connection.c:200:8: note: at offset 128 into destination object ‘TempHexBuffer’ of size 129
  200 |   char TempHexBuffer[(2 * QUIC_TLS_SECRETS_MAX_SECRET_LEN) + 1] = { 0 };
      |        ^~~~~~~~~~~~~

**Comment by qzhuyan** [comment]
don't really understand the warning, which OS/compiler are you using?

**Comment by jlungerer** [comment]
now it seems to compile -> closed
