### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by heiheshang** [emqx/quic#42]
`quicer/c_src/quicer_config.c:324:37: error: passing argument 3 of ‘enif_get_uint64’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   if (!enif_get_uint64(env, evalue, &value0))
/home/pi/erl/24.0.2/usr/include/erl_nif_api_funcs.h:135:89: note: expected ‘ErlNifUInt64 *’ {aka ‘long long unsigned int *’} but argument is of type ‘long unsigned int *’
 ERL_NIF_API_FUNC_DECL(int,enif_get_uint64,(ErlNifEnv*, ERL_NIF_TERM term, ErlNifUInt64* ip));
                                                                           ~~~~~~~~~~~~~~^~
/home/pi/erl/24.0.2/usr/include/erl_nif.h:345:76: note: in definition of macro ‘ERL_NIF_API_FUNC_DECL’
 #  define ERL_NIF_API_FUNC_DECL(RET_TYPE, NAME, ARGS) extern RET_TYPE NAME ARGS
                                                                            ^~~~
cc1: all warnings being treated as errors
make[3]: *** [CMakeFiles/quicer_static.dir/build.make:76: CMakeFiles/quicer_static.dir/c_src/quicer_config.c.o] Error 1
`
erlang 24.0.2
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

**Comment by heiheshang** [comment]
/home/pi/scanner_barcode/_build/default/lib/quicer/c_src/quicer_config.c:324:37: error: passing argument 3 of ‘enif_get_uint64’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   if (!enif_get_uint64(env, evalue, &value0))
                                     ^~~~~~~
In file included from /home/pi/scanner_barcode/_build/default/lib/quicer/c_src/quicer_nif.h:20,
                 from /home/pi/scanner_barcode/_build/default/lib/quicer/c_src/quicer_config.h:20,
                 from /home/pi/scanner_barcode/_build/default/lib/quicer/c_src/quicer_config.c:17:
/home/pi/erl/24.0-rc3/usr/include/erl_nif_api_funcs.h:135:89: note: expected ‘ErlNifUInt64 *’ {aka ‘long long unsigned int *’} but argument is of type ‘long unsigned int *’
 ERL_NIF_API_FUNC_DECL(int,enif_get_uint64,(ErlNifEnv*, ERL_NIF_TERM term, ErlNifUInt64* ip));
                                                                           ~~~~~~~~~~~~~~^~
/home/pi/erl/24.0-rc3/usr/include/erl_nif.h:341:76: note: in definition of macro ‘ERL_NIF_API_FUNC_DECL’
 #  define ERL_NIF_API_FUNC_DECL(RET_TYPE, NAME, ARGS) extern RET_TYPE NAME ARGS
                                                                            ^~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/quicer_static.dir/build.make:76: CMakeFiles/quicer_static.dir/c_src/quicer_config.c.o] Error 1

**Comment by qzhuyan** [comment]
@heiheshang can you pull latest main branch and try again?

**Comment by heiheshang** [comment]
I'm use https://github.com/emqx/emqtt can't choose

**Comment by qzhuyan** [comment]
@heiheshang are you on the latest emqtt? the latest version should have the fix as well. If you have pulled the latest, try `make clean` and `make` which will pull the 0.0.6

**Comment by heiheshang** [comment]
i tried the latest emqtt,the result is the same

**Comment by qzhuyan** [comment]
@heiheshang can you provide the error logs? the old error logs show that it was built with old vsn.

or you can also check  the quicer vsn via 

```
# in emqtt src tree,
cd _build/default/lib/quicer/
git show
```

**Comment by heiheshang** [comment]
git show
commit a17fd83445148161c80a43afda760998f82673c8 (HEAD, tag: 0.0.4)
Merge: eaac10b b9e17cf
Author: William Yang <William.yang@emqx.io>
Date:   Wed Jun 23 15:33:25 2021 +0200

    Merge pull request #41 from qzhuyan/dev/william/setopts
    
    Support set/get socket opt: active
    
    ensure lttng debug lib is loaded with escript

**Comment by qzhuyan** [comment]
@heiheshang that is old vsn, newer one should be `0.0.6`

Your `emqtt` is on which branch/tag? 

just FYI, both latest master of emqtt and tag `1.4.2` should have the `quicer 0.0.6`

**Comment by heiheshang** [comment]
branch master

**Comment by qzhuyan** [comment]
then pls run 

```
git pull
git branch -vv
git remote -v 
git show
```

if you see something like 
```
commit 321a67665111f81ddc124878b1168b635b827b27 (HEAD, tag: 1.4.2, ....
```

then 

```
make clean
ls rebar.lock
make
```

Send me all the outputs, thanks

**Comment by heiheshang** [comment]
yes, I should have switched to version 1.4.2, thanks
